/**
 * DERIVED ACTIVATION VERIFIER — do not edit.
 * Generated by scripts/gen-activation-verifier.mjs. Contains only a scrypt-derived
 * verifier (salt + hash) — the activation code itself is never stored anywhere
 * in this repository, bundle, database, or logs (see docs/SECURITY_MODEL.md §6).
 */
export const ACTIVATION_SALT = 'eDCWIuFGny3vkyVKPLwkOw=='
export const ACTIVATION_VERIFIER = 'GUV49JDOuGQvZVwVX9J7T+OPvxgA4jZe3Hjfft73DwU='
export const ACTIVATION_FINGERPRINT = '8a4539ea253203a2'
export const ACTIVATION_PARAMS = { N: 16384, r: 8, p: 1, keylen: 32 }
